version: '3.5'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            HTTP_PORT: 80
            HTTPS_PORT: 443
            VIRTUAL_HOST_DIRECTORY: /etc/nginx/conf.d
            HOMEPAGE_DIRECTORY: /var/www/homepage
            CERTIFICATE_DIRECTORY: /etc/nginx/certificates
        volumes:
            - .:/app
            - /var/run/docker.sock:/var/run/docker.sock
            - virtual_host:/etc/nginx/conf.d
            - homepage:/var/www/homepage
            - certificates:/etc/nginx/certificates

volumes:
    virtual_host:
    homepage:
    certificates:
