version: '2.1'
executors:
    php:
        docker:
            - image: php:7.3.11-cli-alpine

jobs:
    vendor:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client curl
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: composer
                command: |
                    if [[ ! -f vendor/autoload.php ]]; then
                        curl --location --silent https://getcomposer.org/composer.phar -o /usr/bin/composer; \
                        chmod +x /usr/bin/composer; \
                        composer global require hirak/prestissimo; \
                        composer install --no-progress --no-interaction; \
                    fi
            - save_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - persist_to_workspace:
                root: .
                paths:
                    - vendor

    phpcs:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: phpcs
                command: bin/phpcs

    phpstan:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: phpstan
                command: bin/phpstan

    phpunit:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: phpunit
                command: bin/phpunit
            - store_artifacts:
                path: build
            - store_test_results:
                path: build/phpunit
            - run:
                name: push code coverage report to codecov
                command: |
                    apk add bash
                    curl -s https://codecov.io/bash | bash

workflows:
    version: '2.1'
    tests:
        jobs:
            - vendor
            - phpcs:
                requires:
                    - vendor
            - phpstan:
                requires:
                    - vendor
            - phpunit:
                requires:
                    - vendor
