version: '2.1'
executors:
    php:
        docker:
            - image: php:7.3.8-cli-alpine

jobs:
    vendor:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client curl
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: composer
                command: |
                    if [[ ! -f vendor/autoload.php ]]; then
                        curl --location --silent https://getcomposer.org/composer.phar -o /usr/bin/composer; \
                        chmod +x /usr/bin/composer; \
                        composer global require hirak/prestissimo; \
                        composer install --no-progress --no-interaction; \
                    fi
            - save_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - persist_to_workspace:
                root: .
                paths:
                    - vendor

    phpcs:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: phpcs
                command: bin/phpcs

    phpstan:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: phpstan
                command: bin/phpstan

    phpunit:
        executor: php
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: phpunit
                command: bin/phpunit

    dockerhub:
        docker:
            - image: docker:18.09.7-git
        working_directory: ~/repo
        steps:
            - setup_remote_docker
            - checkout
            - run:
                  name: Authenticate to dockerhub
                  command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_LOGIN} --password-stdin
            - run:
                  name: Build and push docker image
                  command: |
                      version=latest
                      if [[ ! -z ${CIRCLE_TAG} ]]; then \
                          version=${CIRCLE_TAG}; \
                      fi

                      docker_tag=${DOCKERHUB_ORGANIZATION}/${CIRCLE_PROJECT_REPONAME}:${version}

                      docker build . -t ${docker_tag}
                      docker push ${docker_tag}

workflows:
    version: '2.1'
    tests:
        jobs:
            - vendor
            - phpcs:
                requires:
                    - vendor
            - phpstan:
                requires:
                    - vendor
            - phpunit:
                requires:
                    - vendor

    dockerhub:
        jobs:
            - dockerhub:
                  context: global
                  filters:
                      tags:
                          only: /^[0-9]+.[0-9]+.[0-9]+$/
                      branches:
                          only: master
