services:
    _defaults:
        autowire: true
        public: false
        bind:
            $commands: !tagged console.command

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']

    App\Application:
        public: true

    App\Command\ProxyCommand: ~

    App\Command\ProxyServerCommand: ~
